In [1]:
import numpy as np

list1 = [1, 2, 3.7, 4, '5']

arr = np.array(list1)

print(list1)
print(arr)

[1, 2, 3.7, 4, '5']
['1' '2' '3.7' '4' '5']


In [3]:
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
id = np.eye(3)

In [4]:
r_arr = np.arange(0,10,2)
lin_arr = np.linspace(0,100,5)

In [5]:
print(r_arr , lin_arr)

[0 2 4 6 8] [  0.  25.  50.  75. 100.]


In [6]:
array = np.array(
    [[[3,2,1],[4,5,6]],
     [[9,2,31],[4,15,-6]]]
)

In [8]:
print(array.shape)
print(array.ndim)
print(array.size)
print(array.dtype)
print(array[1][0][2])

(2, 2, 3)
3
12
int64
31


In [9]:
arr = np.arange(1,6)

print(arr)



[1 2 3 4 5]


In [11]:
print(arr[1:4])
print(arr[1:-1])


[2 3 4]
[2 3 4]


In [14]:
print(arr[::2])

[1 3 5]


In [15]:
arr2d = np.array([[1,2,3],[4,5,6]])

In [16]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
print(arr2d[0,1])

2


In [25]:
arr2d[:1]

array([[1, 2, 3]])

In [30]:
np.random.seed(50)
rand_arr = np.random.random(5)
rand_arr

array([0.49460165, 0.2280831 , 0.25547392, 0.39632991, 0.3773151 ])

In [31]:
y = np.random.randint(1,7,5)

In [32]:
y

array([6, 6, 3, 3, 5])

In [37]:
z= np.random.normal(50,10,5)

In [38]:
z

array([41.57482086, 47.04506198, 43.1303919 , 58.89520727, 50.87534609])

In [41]:
q = np.arange(1, 6)

In [42]:
choice = np.random.choice(q,3)

In [43]:
choice

array([1, 4, 3])

In [47]:
q = np.array(["가위","바위","보"])

In [ ]:

choice = np.random.choice(q,2)
print(choice)

In [49]:
a = np.arange(1,6)

mask = a>2

print(a[mask])

[3 4 5]


In [53]:
result = np.where(a > 3 , a , a**2)

In [54]:
result

array([1, 4, 9, 4, 5])

In [61]:
b = np.arange(1,13)

In [62]:
r = b.reshape(2,2,3)

In [64]:
r


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
r.T

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [66]:
f = r.flatten()

In [67]:
print(f)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [68]:
m = np.array([4,25,9,16])

In [69]:
print(np.sqrt(m))

[2. 5. 3. 4.]


In [71]:
print(np.exp(m))

[5.45981500e+01 7.20048993e+10 8.10308393e+03 8.88611052e+06]


In [72]:
print(np.log(m))

[1.38629436 3.21887582 2.19722458 2.77258872]


In [73]:
n = np.array([0, np.pi/2, np.pi])

In [74]:
print(n)

[0.         1.57079633 3.14159265]


In [75]:
print(np.sin(n))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [76]:
print(np.cos(n))

[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [79]:
r = m.reshape(2,2)

In [80]:
r

array([[ 4, 25],
       [ 9, 16]])

In [81]:
r.T

array([[ 4,  9],
       [25, 16]])