In [1]:
import numpy as np

list1 = [1, 2, 3.7, 4, '5']

arr = np.array(list1)

print(list1)
print(arr)

[1, 2, 3.7, 4, '5']
['1' '2' '3.7' '4' '5']


In [3]:
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
id = np.eye(3)

In [4]:
r_arr = np.arange(0,10,2)
lin_arr = np.linspace(0,100,5)

In [5]:
print(r_arr , lin_arr)

[0 2 4 6 8] [  0.  25.  50.  75. 100.]


In [6]:
array = np.array(
    [[[3,2,1],[4,5,6]],
     [[9,2,31],[4,15,-6]]]
)

In [8]:
print(array.shape)
print(array.ndim)
print(array.size)
print(array.dtype)
print(array[1][0][2])

(2, 2, 3)
3
12
int64
31


In [9]:
arr = np.arange(1,6)

print(arr)



[1 2 3 4 5]


In [11]:
print(arr[1:4])
print(arr[1:-1])


[2 3 4]
[2 3 4]


In [14]:
print(arr[::2])

[1 3 5]


In [15]:
arr2d = np.array([[1,2,3],[4,5,6]])

In [16]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
print(arr2d[0,1])

2


In [25]:
arr2d[:1]

array([[1, 2, 3]])